import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        brand: {
          DEFAULT: "#16a34a",
          dark: "#15803d",
          light: "#dcfce7",
          50: "#f0fdf4",
        },
        whatsapp: {
          DEFAULT: "#075e54",
          chat: "#e5ddd5",
          bubble: "#dcf8c6",
        },
        // Material Design 3 — Admin panel color system (brand green palette)
        "primary": "#16a34a",
        "on-primary": "#ffffff",
        "primary-container": "#15803d",
        "on-primary-container": "#dcfce7",
        "primary-fixed": "#f0fdf4",
        "primary-fixed-dim": "#dcfce7",
        "on-primary-fixed": "#052e16",
        "on-primary-fixed-variant": "#15803d",
        "inverse-primary": "#86efac",
        "secondary": "#15803d",
        "on-secondary": "#ffffff",
        "secondary-container": "#dcfce7",
        "on-secondary-container": "#052e16",
        "secondary-fixed": "#f0fdf4",
        "secondary-fixed-dim": "#bbf7d0",
        "on-secondary-fixed": "#052e16",
        "on-secondary-fixed-variant": "#15803d",
        "tertiary": "#92400e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b45309",
        "on-tertiary-container": "#fef3c7",
        "tertiary-fixed": "#fef3c7",
        "tertiary-fixed-dim": "#fcd34d",
        "on-tertiary-fixed": "#451a03",
        "on-tertiary-fixed-variant": "#92400e",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface": "#f8fafc",
        "surface-dim": "#e2e8f0",
        "surface-bright": "#f8fafc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f5f9",
        "surface-container": "#e8edf2",
        "surface-container-high": "#dde3ea",
        "surface-container-highest": "#d1d8e0",
        "surface-variant": "#dde3ea",
        "surface-tint": "#16a34a",
        "on-surface": "#0f172a",
        "on-surface-variant": "#475569",
        "inverse-surface": "#1e293b",
        "inverse-on-surface": "#f1f5f9",
        "outline": "#64748b",
        "outline-variant": "#cbd5e1",
        "on-background": "#0f172a",
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "gutter": "20px",
      },
      fontSize: {
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
